framework:
    cache:
        # Optional but recommended so cache keys stay stable across deploys
        # prefix_seed: '%env(APP_NAME)%'

        # Default (will be overridden per env below)
        app: cache.adapter.filesystem

when@prod:
    framework:
        cache:
            app: cache.adapter.redis
            default_redis_provider: '%env(resolve:REDIS_URL)%'
